### ISSUE TITLE
benchmeth and ahoy.track: undefined local variable or method `ahoy' for ApplicationController:Class

### ISSUE THREAD

**Issue by petebytes** [ankane/benchmeth#1]
Another great gem!

Trying to store performance info using an ahoy event (perhaps there is a better way).  And getting an error:
undefined local variable or method `ahoy' for ApplicationController:Class

`Benchmeth.on_benchmark do |method_name, seconds|`
  `puts "#{method_name} took #{seconds} seconds!"`
  `ahoy.track "Benchmark", method_name: method_name, duration: seconds`
`end`

**Comment by ankane** [comment]
Hey @petebytes, Ahoy isn't really designed for this use case, so I wouldn't recommend using it for this. That being said, `Ahoy.instance` may be set in some contexts (like controllers).

**Comment by petebytes** [comment]
Thanks for the quick response
